name: Build And Deploy Testnet

on:
  push:
    branches:
      - develop
      - ci/deploy-testnet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        run: |
          export REGISTY_URL=registry.gitlab.com/blhl1210/hub:d2e-api
          docker build --pull --rm -f "Dockerfile" -t d2e-api:latest "."
          docker login registry.gitlab.com -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker tag d2e-api:latest ${REGISTY_URL}
          docker push ${REGISTY_URL}

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Re-run docker compose
  #     uses: appleboy/ssh-action@v0.1.10
  #     with:
  #       host: ${{ secrets.SSH_HOST }}
  #       username: ${{ secrets.SSH_USERNAME }}
  #       key: ${{ secrets.SSH_PRIVATE_KEY }}
  #       port: ${{ secrets.PORT }}
  #       script: |
  #         sudo docker pull blhl1210/mlem-ui:dev
  #         cd /home/ubuntu/mlem-dashboard && sudo docker compose -f "docker-compose.yml" up -d --build
