name: Build And Deploy API Testnet

on:
  push:
    branches:
      - develop
      - ci/deploy-testnet
      - ci/build-testnet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        run: |
          cd ./apps/server
          export REGISTY_URL=registry.gitlab.com/blhl1210/hub:melem-viction-api
          docker build --pull --rm -f "./Dockerfile" -t melem-viction-api:latest "."
          docker login registry.gitlab.com -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker tag melem-viction-api:latest ${REGISTY_URL}
          docker push ${REGISTY_URL}
